# For local development only.

name: ${PROJECT_PREFIX:-volt}

services:
  volt-dev-8.1:
    container_name: ${PROJECT_PREFIX:-volt}-dev-8.1
    hostname: ${PROJECT_PREFIX:-volt}-dev-81
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.1
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volt-dev-8.2:
    container_name: ${PROJECT_PREFIX:-volt}-dev-8.2
    hostname: ${PROJECT_PREFIX:-volt}-dev-82
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.2
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volt-dev-8.3:
    container_name: ${PROJECT_PREFIX:-volt}-dev-8.3
    hostname: ${PROJECT_PREFIX:-volt}-dev-83
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.3
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volt-dev-8.4:
    container_name: ${PROJECT_PREFIX:-volt}-dev-8.4
    hostname: ${PROJECT_PREFIX:-volt}-dev-84
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.4
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volt-dev-8.5:
    container_name: ${PROJECT_PREFIX:-volt}-dev-8.5
    hostname: ${PROJECT_PREFIX:-volt}-dev-85
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.5
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"
